# routes.yml
route1:
    path:     /
    defaults: { _controller: 'App\GatewayModule\Controllers\DefaultController::indexAction' }

route2:
    path:     /test
    defaults: { _controller: 'App\GatewayModule\Controllers\DefaultController::testAction' }
